### ISSUE TITLE
List

### ISSUE THREAD

**Issue by kiwad** [Hestat/minerchk#3]
You might want to take a look at this project on Gitlab for a larger list
https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/1

Also, in your post : https://laskowski-tech.com/resources/web-server-malware-investigating/
Note that Gravity has been closed. Could suggest sucuri scan instead.

**Comment by Hestat** [comment]
Hell, thank you for the info. I am familiar with Zerodot's list. As this package is aimed at webserver malware I can't pull directly from  the list as is due to IP's used by Cloudflare and other CDN's that if added here would impact legitimate performance.

I have updated my site from Gravity scan though to sucuri, I also enjoy their external scanning and now that Gravity is ended its a pretty good option.
